### PR TITLE
Fix System.InvalidOperationException: This Visual is not connected to…

### PR DESCRIPTION
**Pull request by flash384**
Check that TextView in PresentationSource

```
> System.InvalidOperationException: This Visual is not connected to a PresentationSource.
>     System.Windows.Media.Visual.PointToScreen(Point point)
>     ICSharpCode.AvalonEdit.CodeCompletion.CompletionWindowBase.UpdatePosition()
>     ICSharpCode.AvalonEdit.CodeCompletion.CompletionWindowBase.SetPosition(TextViewPosition position)
>     ICSharpCode.AvalonEdit.CodeCompletion.CompletionWindowBase.OnSourceInitialized(EventArgs e)
>    ICSharpCode.AvalonEdit.CodeCompletion.SharpDevelopCompletionWindow.OnSourceInitialized(EventArgs e)
>     System.Windows.Window.CreateSourceWindow(Boolean duringShow)
>     System.Windows.Window.ShowHelper(Object booleanBox)
>     ICSharpCode.AvalonEdit.CodeCompletion.CodeCompletionEditorAdapter.<>c__DisplayClass2.b__1()
>     System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>     System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### CODE REVIEW

**Comment by flash384** [comment]
Some of tests(WeakReferenceTests) failed without my changes, any idea?

**Comment by jogibear9988** [comment]
I think the failing tests are already fixed. Can this be closed?

**Comment by siegfriedpammer** [comment]
@flash384 The fix looks good to me, but do you have reproduction steps for this bug? Possibly using the AvalonEdit.Sample application? Thank you very much!

**Comment by flash384** [comment]
> @flash384 The fix looks good to me, but do you have reproduction steps for this bug? Possibly using the AvalonEdit.Sample application? Thank you very much!

Hi! Unfortunately I don't have repro steps.

**Comment by dgosbell** [comment]
I'm getting crash reports from my app with this error, but I don't have repro steps either. I can only guess that it's some specific sequence of events with a specific timing or something like that. But it would be great to have this pull request merged in as this issue crashes the hosting application.

**Comment by dgosbell** [comment]
I actually just saw this exception on my app for the first time. But all I did was attempt to reposition the app by dragging the title bar, as far as I can recall the code completion window was not open at the time and I have not been able to repro this again. It makes me wonder if it's only triggered in rare circumstances by some sort of race condition.

**Comment by dgrunwald** [comment]
It's a bit weird to have no `PresentationSource` within the `OnSourceInitialized` event.
Maybe the event can sometimes be delayed in the dispatcher's queue?
Let's hope this fix works. If it's a race with some other WPF thread, the fix might be insufficient and we'd have to instead catch the exception :/

**Comment by XspeedPL** [comment]
I recently ran into this problem and figured out steps that reproduce it:
1. Maximize the parent window
2. Open an OverloadInsightWindow
3. Remove the editor control from the tree (the overload window stays)
4. Try to normalize the window
5. *BOOM*

**Pull request merged**
