### PR TITLE
Implement basic font rendering tuning for code editor.

### PR DESCRIPTION
**Pull request by 13-beta2**
Ability to disable anti-aliasing for 'pixel-perfect' fonts like Courier
New.
Ability to disable hinting to forget about jagged default WPF rendering.

_I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the #develop open source product (the "Contribution"). My Contribution is licensed under the MIT License._

### CODE REVIEW

**Comment by dgrunwald** [comment]
Why should this be part of AvalonEdit? Especially the "CurrentZoom" hack doesn't seem like it belongs into the library. (what about zoom controls using a different property name?)

The TextOptions are usually set on the whole Window and then are inherited into all controls (including AvalonEdit); so I don't see a need to override the TextOptions from within AvalonEdit.

If you are using AvalonEdit within a zoom control that needs to dynamically switch the TextOptions, that feature should be part of the zoom control, not AvalonEdit.

**Comment by 13-beta2** [comment]
Thanks for your feedback! You are right, I'm not very familiar with #develop architecture and could do some stupid mistakes. I'll try to correct this feature using your suggestions.

**Comment by 13-beta2** [comment]
> If you are using AvalonEdit within a zoom control that needs to dynamically switch the TextOptions, that feature should be part of the zoom control, not AvalonEdit.

Main logic moved to zoom widget (https://github.com/icsharpcode/SharpDevelop/pull/733). AE has only one property binding. Is it ok now?

**Comment by dgrunwald** [comment]
Why does AvalonEdit need this binding?

AFAIK the `TextOptions.TextFormattingMode` property is automatically inherited through the visual tree, so you should be able to get this to work without any change to AvalonEdit at all.

**Comment by 13-beta2** [comment]
I don like this binding too. And the only way I see to remove explicit property setter is to change `TextOptions.*` for logical parent.

My studies has shown that parent for AE is `SharpDevelopTextEditor`. Moreover `TextFormattingMode` has already been overridden there (via `ZoomLevelToTextFormattingModeConverter`). So I can just append more complex logic to template ('\src\AddIns\DisplayBindings\AvalonEdit.AddIn\themes\generic.xaml'). This will remove requirement to bind explicitly. But I cant find does '\src\AddIns\DisplayBindings\AvalonEdit.AddIn\\*' subtree should be considered as a part of SD or still as part of AE project?

Main disadvantage is that all other text within `SharpDevelopTextEditor` will remain be inconsistent with rest of UI. Eg I believe that reset zoom button should looks like any other button/label.

**Comment by dgrunwald** [comment]
The AvalonEdit rendering mode can be controlled by setting `TextOptions.TextFormattingMode` and letting WPF property inheritance do its work. I don't see any need for a change in AvalonEdit here.

**Pull request closed without merging**
