### PR TITLE
Change selection behavior when double clicking inside whitespace

### PR DESCRIPTION
**Pull request by jimfoye**
This makes selecting text with a double-click more consistent with Visual Studio, when whitespace is involved. If there is whitespace on both sides of the position, then it selects that whitespace instead of jumping backwards and selecting characters that are not under the mouse.

From a user standpoint, just imagine having a lot of of whitespace between two words, and wanting to replace it with a single space. The easiest and most natural thing to do is to double click anywhere between the words to select all the whitespace, then press space to replace it.

### CODE REVIEW

**Comment by dgrunwald** [comment]
First of all, sorry for taking so long to get back to you on this.

I agree with changing the selection logic, but I can see this patch causing problems with custom `VisualLineElement`s that don't correspond to any document text, and are embedded at a location surrounded by whitespace, and report internal caret stops. (I'm not sure if anyone is using such a thing with AvalonEdit, but the "code generation options" panel in SharpDevelop comes somewhat close)

I think it would be better to always ask the `VisualLine` for caret stops, and then select the intersection of the whitespace segment with segment reported by the `VisualLine`; so that this change limits the selection to the whitespace, but does not extend it if already limited by custom `VisualLineElement`s.

**Comment by jimfoye** [comment]
Thanks for the feedback.

**Comment by jimfoye** [comment]
If I just simplify my code by removing the first block of the if statement and then change the first call to GetNextCaretPosition(), passing CaretPositioningMode.WordBorderOrSymbol instead of CaretPositioningMode.WordStartOrSymbol, I get the same (desired) result. So obviously this is better because it's simpler, but aside from that, do you think this works for custom scenarios? Or is something additional still needed?

My revised code would look something like this:

` 

            if (line != null)
            {
                int visualColumn = line.GetVisualColumn(pos, textArea.Selection.EnableVirtualSpace);
                int relOffset = line.FirstDocumentLine.Offset;

                int wordStartVC = line.GetNextCaretPosition(visualColumn + 1, 
                                                            LogicalDirection.Backward, 
                                                            CaretPositioningMode.WordBorderOrSymbol, 
                                                            false);
                if (wordStartVC == -1)
                    wordStartVC = 0;

                int wordEndVC = line.GetNextCaretPosition(wordStartVC, 
                                                          LogicalDirection.Forward, 
                                                          CaretPositioningMode.WordBorderOrSymbol, 
                                                          false);
                if (wordEndVC == -1)
                    wordEndVC = line.VisualLength;

                int wordStartOffset = line.GetRelativeOffset(wordStartVC) + relOffset;
                int wordEndOffset = line.GetRelativeOffset(wordEndVC) + relOffset;

                return new SimpleSegment(wordStartOffset, wordEndOffset - wordStartOffset);
            }
            else
                return SimpleSegment.Invalid;
`

**Comment by jimfoye** [comment]
Oh, one note about the code in my last comment, I was experimenting with replacing

'textArea.Selection.EnableVirtualSpace' with 'false', as at this point in the code, there is by definition no selection (i.e., it should always be empty, so EnableVirtualSpace always false). I'm fine with not making this change part of the PR.

**Comment by dgrunwald** [comment]
Just replacing `WordStartOrSymbol` with `WordBorderOrSymbol` causes double-clicks on a single space to select the space. In VS such clicks will select the nearest word; only multiple consecutive spaces can be selected.
This function also affects the "double-click-and-drag" selection mode: extending the selection should extend it word-by-word, without intermediate steps where the selection ends with a single trailing space.

About `EnableVirtualSpace`: this can still be `true` for an empty selection if virtual space is enabled in the `TextEditorOptions`. However, this selection mode should never select virtual space, so it's OK to pass false here.

**Comment by jimfoye** [comment]
@dgrunwald 

`
I think it would be better to always ask the VisualLine for caret stops, and then select the intersection of the whitespace segment with segment reported by the VisualLine; so that this change limits the selection to the whitespace, but does not extend it if already limited by custom VisualLineElements.
`

Unfortunately I make no use of VisualLineElement myself, and have had some trouble figuring out how to implement your suggested approach. I am fine with you taking over this task. Alternatively, if you can provide some more specifics on what I actually need to do (maybe some code would be best) I can take another run at finishing this PR. Either way is OK with me.

**Pull request closed without merging**
