### PR TITLE
Add Python definition

### PR DESCRIPTION
**Pull request by heldersepu**
Fixes Issue #111

### CODE REVIEW

**Comment by dgrunwald** [comment]
Can you add some more features to make this a complete language definition?

On a quick look, it's missing: multi-line string literals; and maybe some keywords (e.g. `nonlocal`).

**Comment by heldersepu** [comment]
Sure...
Can you provide a sample .py file with the missing features

On Mar 12, 2017 9:07 AM, "Daniel Grunwald" <notifications@github.com> wrote:

Can you add some more features to make this a complete language definition?

On a quick look, it's missing: multi-line string literals; and maybe some
keywords (e.g. nonlocal).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/icsharpcode/AvalonEdit/pull/112#issuecomment-285943493>,
or mute the thread

**Comment by heldersepu** [comment]
@dgrunwald Not sure why the checks are failing...
the details does not show much that info either, Do you know what could be wrong?

**Comment by heldersepu** [comment]
Closing this PR will reopen a new one

**Pull request closed without merging**
