### PR TITLE
feature netcore3 support

### PR DESCRIPTION
**Pull request by jogibear9988**
todo:

- documentation does not compile 
- nrefactoy in wpf build

### CODE REVIEW

**Comment by dgrunwald** [comment]
I have no idea why the weak reference tests started failing.
Either something in WPF changed and introduced a memory leak; or something in .NET changed regarding the GC, and we can no longer test that an object gets collected as expected.
Oh, and just now I remembered: it's also possible that the test itself is keeping stuff alive. I remember having problems like that with `DocumentDoesNotHoldReferenceToLineMargin`, e.g. because use object initializers involve an extra temporary that maintains a reference. Maybe the problem is just that the `textView = null;` started getting optimized out? Possibly by Roslyn, or possibly by updates to the .NET JIT.
I guess a clean test would have to use the approach from `DocumentDoesNotHoldReferenceToLineMargin` and reference the object-to-be-collected only inside a separate method (which probably should be marked `[MethodImpl(MethodImplOptions.NoInlining)]` for extra safety).

**Comment by jogibear9988** [comment]
Inside of Visual Studio the test works. (on my system).


Von meinem iPhone gesendet

**Comment by dgrunwald** [comment]
If it's a compiler optimization, it might depend on debug/release.
If it's a JIT optimization, it also might depend on whether a debugger is attached.
So that would indicate that it might be a problem with `textView = null;` getting optimized out.

**Comment by christophwille** [comment]
I tried locally with a Release build - that works too. My bet would be on the JIT.

**Comment by jogibear9988** [comment]
For the moment, I think the warning when the tests fail  is the best solution if no one has time to look after

 

Von: Christoph Wille <notifications@github.com>
Antworten an: icsharpcode/AvalonEdit <reply@reply.github.com>
Datum: Sonntag, 5. Mai 2019 um 13:00
An: icsharpcode/AvalonEdit <AvalonEdit@noreply.github.com>
Cc: Jochen Kühner <jochen.kuehner@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [icsharpcode/AvalonEdit] feature netcore3 support (#168)

 

I tried locally with a Release build - that works too. My bet would be on the JIT.

**Comment by dgrunwald** [comment]
Note: the readme should be updated to explain what to install, so that AvalonEdit can be built.
In particular when opening the solution in VS requires unusual steps like installing a preview version of a .NET SDK...

**Comment by christophwille** [comment]
@dgrunwald I have amended readme.md with a short section on How to build.

WeakReferenceTests: would be great if you could try to fix those - having full unit test coverage back would be very reassuring.

**Comment by christophwille** [comment]
I have added a separate issue for removing old code (#if NREFACTORY see https://github.com/icsharpcode/AvalonEdit/issues/174) - with that, anything missing for merging this? Tests run again thanks to Daniel, SHFB doc generation works again, all artefacts are produced (nupkg, snupkg, source code links)

**Pull request merged**
