### PR TITLE
Added basic UI Automation TextPattern support.

### PR DESCRIPTION
**Pull request by glenrgordon**
This provides basic UI Automation Text Pattern support for AvalonEdit.  I say basic because it doesn't properly deal with hidden regions, autocompletion etc.  My interest was in being able to read source code in ILSpy and these changes allow that.

### CODE REVIEW

**Comment by dgrunwald** [comment]
I'm a bit clueless about UI automation. How would I test these changes?

Is it intentional that we need automation peers for both TextArea and TextEditor?

**Comment by glenrgordon** [comment]
Hi, Daniel,

 

Thanks so much for getting back to me on this.

 

By way of background, I’m the original author of the JAWS screen reader for the blind.

I’m blind myself and actually made these changes so I could move away  from Reflector.

They are by no means complete and only handle a subset of AvalonEdit’s functionality.

But with them, I can actually use JAWS to read disassembled code in ILSpy.

 

Now to your questions:

There’s a one to one peering relationship between UIAutomation and the controls that they represent.

Because WPF focus is actually on the internal TextArea, that’s the one that needs to implement the ITextProvider pattern.

ITextProvider is the thing that allows Screen Readers to traverse the text area in bite-sized portions: line/word/character.

 

Two tools from the Windows SDK will help here.

AccEvent will show you the UIA events that are fired as one navigates around the UI with the keyboard.  Make sure that the tool is in UI Automation mode, which it is by default.

Focus events are the ones of greatest interest.

 

The Inspect tool will let you navigate the UIA hierarchy of the application and exercise the various methods of the ITextProvider pattern.

 

I was about to tell you that you could use Windows Narrator to verify that one can traverse an editable region with the keyboard and hear the text being read aloud, but decided maybe I better test with it myself first.

Turns out that it requires  firing of a UIAutomation TextSelectionChanged event that I hadn’t added since JAWS doesn’t require it.

I will make that change in the next couple of weeks and submit it.

With that, Narrator should be a reasonable thing to use to verify.

 

JAWS does have a 40 minute mode which all downloaded versions will run in should you decide to use it to verify instead, but that seems a rather onerous thing to ask of you.

 

 

--Glen

**Comment by dgrunwald** [comment]
Thanks for the explanation.

I fixed some issues with your code -- I was getting out-of-bounds exception when moving the caret near the start/end of the document while Narrator was running.

I also added the TextSelectionChanged event. Narrator now spells out individual letters when moving the caret, but I couldn't get it to speak whole words/lines.

**Comment by glenrgordon** [comment]
Sorry for the out-of-bounds events.  Didn’t get those with JAWS.

 

Thanks for your continued help.

--Glen

**Comment by dgrunwald** [comment]
Closing, as this was merged in a7babb3fd32c59fea59c95879b43e6c5adaf9651.

**Pull request closed without merging**
