### PR TITLE
Support RTL

### PR DESCRIPTION
**Pull request by gheyret**

### CODE REVIEW

**Comment by dgrunwald** [comment]
It's impossible to review this PR due to the excessive formatting changes.

**Comment by dgrunwald** [comment]
Is this a duplicate of #308 or are there additional changes in here?

**Comment by jogibear9988** [comment]
@dgrunwald If you remove the whitespace changes in the github UI it's not so big. But the question is, should the whitespace changes be merged?

**Comment by dgrunwald** [comment]
I have already merged #308

**Comment by jogibear9988** [comment]
this is different in #308: https://github.com/icsharpcode/AvalonEdit/pull/370/files#diff-4b1414766415454746a129601a78d6175fe7b421484f2081f58182c2f8f6a8c1

**Pull request closed without merging**
