### PR TITLE
Adding python definition

### PR DESCRIPTION
**Pull request by heldersepu**
Fixes Issue #111

### CODE REVIEW

**Comment by jimfoye** [comment]
@heldersepu That looks like some problem with the build system, I don't think it has anything to do with your code.

**Comment by heldersepu** [comment]
@jimfoye @dgrunwald  Any chanse this PR can be merged soon?
I also have another PR #107

**Comment by jimfoye** [comment]
I'm not a maintainer, actually (:

**Comment by dgrunwald** [comment]
The Python .xshd looks good; thanks!

I'll have to take a closer look at your change to FoldingManager.cs. The new code certainly seems to make more sense, but we've had problems with this in the past, so I want to treat carefully here.

**Comment by heldersepu** [comment]
@dgrunwald 
I can't remember why I changed the FoldingManager.cs, I'm looking into it...

**Comment by heldersepu** [comment]
@dgrunwald 
Take a look at this:
https://github.com/heldersepu/AvalonEdit/commit/9c55316d14f8a5aecd3ed9c35c0df745b4fe4e67
It seem it was when I did a merge

**Comment by heldersepu** [comment]
@dgrunwald 
You should be able to merge this PR without looking into the FoldingManager.cs 
When can we expect an update to the NuGet Package?

**Comment by jogibear9988** [comment]
i think the change of foldingmanger is also in this pull req: https://github.com/icsharpcode/AvalonEdit/pull/87/commits

**Pull request merged**
