### PR TITLE
Feature/fixes

### PR DESCRIPTION
**Pull request by jogibear9988**
Multiple fixes, should be merged only after netcore 3 port

### CODE REVIEW

**Comment by jogibear9988** [comment]
fixes #20, obsolete #124

**Comment by christophwille** [comment]
AppVeyor fails on Debug builds: https://ci.appveyor.com/project/icsharpcode/avalonedit/builds/25180893 - 129 out of 185 run, then it seems to be "gone". There has to be a change in here that makes Debug unit tests crash vs work a-ok on Release builds.

**Comment by jogibear9988** [comment]
@christophwille now it's fixed.
can I merge?

**Comment by christophwille** [comment]
@dgrunwald please have a quick look at it (&merge if ok)

**Comment by jogibear9988** [comment]
@dgrunwald is it okay to merge?

**Comment by jogibear9988** [comment]
@christophwille it's not enough if you review?

**Comment by christophwille** [comment]
I can't do a techical review for AvalonEdit (way too little knowledge about architecture and code base)

**Pull request merged**
